-- Master data. Apply after schema.sql. The API creates these on startup too;
-- this file is here so the schema can be read, reviewed and applied by hand.
--
-- CUSTOMER_MASTER, EMPLOYEE_MASTER, PRODUCT_MASTER_BRAND and PRODUCT_MASTER are
-- the tables of MASTER DATA & TABLES.xlsx, with its table and column names
-- (EMPLOYEE_MASTER without PASSWORD, which is never stored). Their ZONE_ID,
-- HQ_ID, TERRITORY_ID, PRODUCT_GROUP_ID, TEAM_ID, ROLE_ID and DESIGNATION_ID
-- hold the parent's Master ID (LegacyId on the md_* table).
--
-- Structure (permanent):  Zone > Headquarter > Territory
--                         Product group > PRODUCT_MASTER_BRAND > PRODUCT_MASTER
-- Alignment (per year):   every table with a YearId.
--
-- Generated from app/models_master.py with the MySQL dialect, so it matches.


CREATE TABLE IF NOT EXISTS `CUSTOMER_MASTER` (
	`CUSTOMER_ID` INTEGER NOT NULL AUTO_INCREMENT, 
	`CUSTOMER_NAME` VARCHAR(200) NOT NULL, 
	`CUSTOMER_SAP_ID` VARCHAR(50), 
	`ZONE_ID` INTEGER, 
	`HQ_ID` INTEGER, 
	`TERRITORY_ID` INTEGER, 
	`SUB_TERRITORY_ID` INTEGER, 
	`CUSTOMER_BILLING_NAME` VARCHAR(200), 
	`STATE_ID` INTEGER, 
	`CUST_CLASSIFICATION_ID` INTEGER, 
	`CUST_REMARK_ID` INTEGER, 
	`CUSTOMER_ALIAS_1` VARCHAR(200), 
	`CUSTOMER_ALIAS_2` VARCHAR(200), 
	`CUSTOMER_ALIAS_3` VARCHAR(200), 
	`CUSTOMER_ALIAS_4` VARCHAR(200), 
	`CUSTOMER_ALIAS_5` VARCHAR(200), 
	`CUSTOMER_ALIAS_6` VARCHAR(200), 
	`CUSTOMER_ALIAS_7` VARCHAR(200), 
	`CUSTOMER_ALIAS_8` VARCHAR(200), 
	`CUSTOMER_ALIAS_9` VARCHAR(200), 
	`CUSTOMER_ALIAS_10` VARCHAR(200), 
	`CUSTOMER_ALIAS_11` VARCHAR(200), 
	`CUSTOMER_ALIAS_12` VARCHAR(200), 
	`CUSTOMER_ALIAS_13` VARCHAR(200), 
	`CUSTOMER_ALIAS_14` VARCHAR(200), 
	`CUSTOMER_ALIAS_15` VARCHAR(200), 
	`CUSTOMER_ALIAS_16` VARCHAR(200), 
	`CUSTOMER_ALIAS_17` VARCHAR(200), 
	`CUSTOMER_ALIAS_18` VARCHAR(200), 
	`CUSTOMER_ALIAS_19` VARCHAR(200), 
	`CUSTOMER_ALIAS_20` VARCHAR(200), 
	`CUSTOMER_ALIAS_21` VARCHAR(200), 
	`CUSTOMER_ALIAS_22` VARCHAR(200), 
	`CUSTOMER_ALIAS_23` VARCHAR(200), 
	`CUSTOMER_ALIAS_24` VARCHAR(200), 
	`CUSTOMER_ALIAS_25` VARCHAR(200), 
	`CUSTOMER_ALIAS_26` VARCHAR(200), 
	`CUSTOMER_ALIAS_27` VARCHAR(200), 
	`CUSTOMER_ALIAS_28` VARCHAR(200), 
	`CUSTOMER_ALIAS_29` VARCHAR(200), 
	`CUSTOMER_ALIAS_30` VARCHAR(200), 
	`CUSTOMER_ALIAS_31` VARCHAR(200), 
	`CUSTOMER_ALIAS_32` VARCHAR(200), 
	`CUSTOMER_ALIAS_33` VARCHAR(200), 
	`CUSTOMER_ALIAS_34` VARCHAR(200), 
	`CUSTOMER_ALIAS_35` VARCHAR(200), 
	`CUSTOMER_ALIAS_36` VARCHAR(200), 
	`CUSTOMER_ALIAS_37` VARCHAR(200), 
	`CUSTOMER_ALIAS_38` VARCHAR(200), 
	`CUSTOMER_ALIAS_39` VARCHAR(200), 
	`CUSTOMER_ALIAS_40` VARCHAR(200), 
	`CUSTOMER_ALIAS_41` VARCHAR(200), 
	`CUSTOMER_ALIAS_42` VARCHAR(200), 
	`CUSTOMER_ALIAS_43` VARCHAR(200), 
	`CUSTOMER_ALIAS_44` VARCHAR(200), 
	`CUSTOMER_ALIAS_45` VARCHAR(200), 
	`CUSTOMER_ALIAS_46` VARCHAR(200), 
	`CUSTOMER_ALIAS_47` VARCHAR(200), 
	`CUSTOMER_ALIAS_48` VARCHAR(200), 
	`CUSTOMER_ALIAS_49` VARCHAR(200), 
	`CUSTOMER_ALIAS_50` VARCHAR(200), 
	`START_DATE` DATE, 
	`END_DATE` DATE, 
	`STATUS` INTEGER NOT NULL, 
	PRIMARY KEY (`CUSTOMER_ID`)
);

CREATE INDEX ix_customer_master_name ON `CUSTOMER_MASTER` (`CUSTOMER_NAME`);

CREATE TABLE IF NOT EXISTS `EMPLOYEE_MASTER` (
	`EMPLOYEE_ID` INTEGER NOT NULL AUTO_INCREMENT, 
	`EMPLOYEE_FT_NM` VARCHAR(80) NOT NULL, 
	`EMPLOYEE_LT_NM` VARCHAR(80), 
	`EMAIL` VARCHAR(120), 
	`STATUS` INTEGER NOT NULL, 
	`ROLE_ID` INTEGER, 
	`DESIGNATION_ID` INTEGER, 
	`START_DATE` DATE, 
	`END_DATE` DATE, 
	`TEAM` VARCHAR(80), 
	`REPORTING_MANAGER_ID` INTEGER, 
	`RD_CS_EDITABLE` INTEGER NOT NULL, 
	`EMPLOYEE_CODE` VARCHAR(30), 
	`TERRITORY_CODE` VARCHAR(30), 
	PRIMARY KEY (`EMPLOYEE_ID`)
);

CREATE TABLE IF NOT EXISTS `PRODUCT_MASTER` (
	`PRODUCT_ID` INTEGER NOT NULL AUTO_INCREMENT, 
	`SAP_PRODUCT_NAME` VARCHAR(250) NOT NULL, 
	`PRODUCT_ALIAS_1` VARCHAR(250), 
	`PRODUCT_ALIAS_2` VARCHAR(250), 
	`PRODUCT_ALIAS_3` VARCHAR(250), 
	`PRODUCT_ALIAS_4` VARCHAR(250), 
	`PRODUCT_ALIAS_5` VARCHAR(250), 
	`PRODUCT_ALIAS_6` VARCHAR(250), 
	`PRODUCT_ALIAS_7` VARCHAR(250), 
	`PRODUCT_ALIAS_8` VARCHAR(250), 
	`PRODUCT_ALIAS_9` VARCHAR(250), 
	`PRODUCT_ALIAS_10` VARCHAR(250), 
	`PRODUCT_ALIAS_11` VARCHAR(250), 
	`PRODUCT_ALIAS_12` VARCHAR(250), 
	`PRODUCT_ALIAS_13` VARCHAR(250), 
	`PRODUCT_ALIAS_14` VARCHAR(250), 
	`PRODUCT_ALIAS_15` VARCHAR(250), 
	`PRODUCT_ALIAS_16` VARCHAR(250), 
	`PRODUCT_ALIAS_17` VARCHAR(250), 
	`PRODUCT_ALIAS_18` VARCHAR(250), 
	`PRODUCT_ALIAS_19` VARCHAR(250), 
	`PRODUCT_ALIAS_20` VARCHAR(250), 
	`PRODUCT_ALIAS_21` VARCHAR(250), 
	`PRODUCT_ALIAS_22` VARCHAR(250), 
	`PRODUCT_ALIAS_23` VARCHAR(250), 
	`PRODUCT_ALIAS_24` VARCHAR(250), 
	`PRODUCT_ALIAS_25` VARCHAR(250), 
	`PRODUCT_ALIAS_26` VARCHAR(250), 
	`PRODUCT_ALIAS_27` VARCHAR(250), 
	`PRODUCT_ALIAS_28` VARCHAR(250), 
	`PRODUCT_ALIAS_29` VARCHAR(250), 
	`PRODUCT_ALIAS_30` VARCHAR(250), 
	`PRODUCT_ALIAS_31` VARCHAR(250), 
	`PRODUCT_ALIAS_32` VARCHAR(250), 
	`PRODUCT_ALIAS_33` VARCHAR(250), 
	`PRODUCT_ALIAS_34` VARCHAR(250), 
	`PRODUCT_ALIAS_35` VARCHAR(250), 
	`PRODUCT_ALIAS_36` VARCHAR(250), 
	`PRODUCT_ALIAS_37` VARCHAR(250), 
	`PRODUCT_ALIAS_38` VARCHAR(250), 
	`PRODUCT_ALIAS_39` VARCHAR(250), 
	`PRODUCT_ALIAS_40` VARCHAR(250), 
	`PRODUCT_ALIAS_41` VARCHAR(250), 
	`PRODUCT_ALIAS_42` VARCHAR(250), 
	`PRODUCT_ALIAS_43` VARCHAR(250), 
	`PRODUCT_ALIAS_44` VARCHAR(250), 
	`PRODUCT_ALIAS_45` VARCHAR(250), 
	`PRODUCT_ALIAS_46` VARCHAR(250), 
	`PRODUCT_ALIAS_47` VARCHAR(250), 
	`PRODUCT_ALIAS_48` VARCHAR(250), 
	`PRODUCT_ALIAS_49` VARCHAR(250), 
	`PRODUCT_ALIAS_50` VARCHAR(250), 
	`PRODUCT_ALIAS_51` VARCHAR(250), 
	`PRODUCT_ALIAS_52` VARCHAR(250), 
	`PRODUCT_ALIAS_53` VARCHAR(250), 
	`PRODUCT_ALIAS_54` VARCHAR(250), 
	`PRODUCT_ALIAS_55` VARCHAR(250), 
	`PRODUCT_ALIAS_56` VARCHAR(250), 
	`PRODUCT_ALIAS_57` VARCHAR(250), 
	`PRODUCT_ALIAS_58` VARCHAR(250), 
	`PRODUCT_ALIAS_59` VARCHAR(250), 
	`PRODUCT_ALIAS_60` VARCHAR(250), 
	`PRODUCT_ALIAS_61` VARCHAR(250), 
	`PRODUCT_ALIAS_62` VARCHAR(250), 
	`PRODUCT_ALIAS_63` VARCHAR(250), 
	`PRODUCT_ALIAS_64` VARCHAR(250), 
	`PRODUCT_ALIAS_65` VARCHAR(250), 
	`PRODUCT_ALIAS_66` VARCHAR(250), 
	`PRODUCT_ALIAS_67` VARCHAR(250), 
	`PRODUCT_ALIAS_68` VARCHAR(250), 
	`PRODUCT_ALIAS_69` VARCHAR(250), 
	`PRODUCT_ALIAS_70` VARCHAR(250), 
	`PRODUCT_ALIAS_71` VARCHAR(250), 
	`PRODUCT_ALIAS_72` VARCHAR(250), 
	`PRODUCT_ALIAS_73` VARCHAR(250), 
	`PRODUCT_ALIAS_74` VARCHAR(250), 
	`PRODUCT_ALIAS_75` VARCHAR(250), 
	`PRODUCT_ALIAS_76` VARCHAR(250), 
	`PRODUCT_ALIAS_77` VARCHAR(250), 
	`PRODUCT_ALIAS_78` VARCHAR(250), 
	`PRODUCT_ALIAS_79` VARCHAR(250), 
	`PRODUCT_ALIAS_80` VARCHAR(250), 
	`PRODUCT_ALIAS_81` VARCHAR(250), 
	`PRODUCT_ALIAS_82` VARCHAR(250), 
	`PRODUCT_ALIAS_83` VARCHAR(250), 
	`PRODUCT_ALIAS_84` VARCHAR(250), 
	`PRODUCT_ALIAS_85` VARCHAR(250), 
	`PRODUCT_ALIAS_86` VARCHAR(250), 
	`PRODUCT_ALIAS_87` VARCHAR(250), 
	`PRODUCT_ALIAS_88` VARCHAR(250), 
	`PRODUCT_ALIAS_89` VARCHAR(250), 
	`PRODUCT_ALIAS_90` VARCHAR(250), 
	`PRODUCT_ALIAS_91` VARCHAR(250), 
	`PRODUCT_ALIAS_92` VARCHAR(250), 
	`PRODUCT_ALIAS_93` VARCHAR(250), 
	`PRODUCT_ALIAS_94` VARCHAR(250), 
	`PRODUCT_ALIAS_95` VARCHAR(250), 
	`PRODUCT_ALIAS_96` VARCHAR(250), 
	`PRODUCT_ALIAS_97` VARCHAR(250), 
	`PRODUCT_ALIAS_98` VARCHAR(250), 
	`PRODUCT_ALIAS_99` VARCHAR(250), 
	`PRODUCT_ALIAS_100` VARCHAR(250), 
	`PRODUCT_BRAND_ID` INTEGER, 
	`PRODUCT_GROUP_ID` INTEGER, 
	`SAP_PRODUCT_ID` VARCHAR(30), 
	`NRV` NUMERIC(18, 4), 
	`START_DATE` DATE, 
	`END_DATE` DATE, 
	`STATUS` INTEGER NOT NULL, 
	`MATERIAL_CODE` VARCHAR(50), 
	PRIMARY KEY (`PRODUCT_ID`)
);

CREATE INDEX `ix_PRODUCT_MASTER_PRODUCT_BRAND_ID` ON `PRODUCT_MASTER` (`PRODUCT_BRAND_ID`);

CREATE TABLE IF NOT EXISTS `PRODUCT_MASTER_BRAND` (
	`PRODUCT_BRAND_ID` INTEGER NOT NULL AUTO_INCREMENT, 
	`PRODUCT_BRAND_NAME` VARCHAR(120) NOT NULL, 
	`PRODUCT_GROUP_ID` INTEGER, 
	`START_DATE` DATE, 
	`END_DATE` DATE, 
	`STATUS` INTEGER NOT NULL, 
	`REPORTING` VARCHAR(30), 
	`TEAM_ID` INTEGER, 
	`NRV` VARCHAR(30), 
	`NO_OF_SKU` INTEGER, 
	PRIMARY KEY (`PRODUCT_BRAND_ID`)
);

CREATE TABLE IF NOT EXISTS md_company (
	`Id` INTEGER NOT NULL AUTO_INCREMENT, 
	`Code` VARCHAR(20) NOT NULL, 
	`Name` VARCHAR(120) NOT NULL, 
	`Active` INTEGER NOT NULL, 
	PRIMARY KEY (`Id`), 
	CONSTRAINT uq_company_code UNIQUE (`Code`)
);

CREATE TABLE IF NOT EXISTS md_country (
	`Id` INTEGER NOT NULL AUTO_INCREMENT, 
	`Code` VARCHAR(20) NOT NULL, 
	`Name` VARCHAR(80) NOT NULL, 
	`CurrencyCode` VARCHAR(3) NOT NULL, 
	`Active` INTEGER NOT NULL, 
	PRIMARY KEY (`Id`), 
	CONSTRAINT uq_country_code UNIQUE (`Code`)
);

CREATE TABLE IF NOT EXISTS md_currency_rate (
	`Id` INTEGER NOT NULL AUTO_INCREMENT, 
	`FromCurrency` VARCHAR(3) NOT NULL, 
	`ToCurrency` VARCHAR(3) NOT NULL, 
	`Rate` NUMERIC(18, 6) NOT NULL, 
	`EffectiveFrom` DATE NOT NULL, 
	`Note` VARCHAR(200), 
	PRIMARY KEY (`Id`), 
	CONSTRAINT uq_rate_pair_date UNIQUE (`FromCurrency`, `ToCurrency`, `EffectiveFrom`)
);

CREATE TABLE IF NOT EXISTS md_designation (
	`Id` INTEGER NOT NULL AUTO_INCREMENT, 
	`Code` VARCHAR(20) NOT NULL, 
	`Name` VARCHAR(80) NOT NULL, 
	`Level` INTEGER NOT NULL, 
	`LegacyId` INTEGER, 
	`Active` INTEGER NOT NULL, 
	PRIMARY KEY (`Id`), 
	CONSTRAINT uq_designation_code UNIQUE (`Code`)
);

CREATE TABLE IF NOT EXISTS md_role (
	`Id` INTEGER NOT NULL AUTO_INCREMENT, 
	`Code` VARCHAR(20) NOT NULL, 
	`Name` VARCHAR(80) NOT NULL, 
	`Description` VARCHAR(300), 
	`LegacyId` INTEGER, 
	`Active` INTEGER NOT NULL, 
	PRIMARY KEY (`Id`), 
	CONSTRAINT uq_role_code UNIQUE (`Code`)
);

CREATE TABLE IF NOT EXISTS md_year (
	`Id` INTEGER NOT NULL AUTO_INCREMENT, 
	`YearValue` INTEGER NOT NULL, 
	`Label` VARCHAR(40) NOT NULL, 
	`StartDate` DATE NOT NULL, 
	`EndDate` DATE NOT NULL, 
	`IsCurrent` INTEGER NOT NULL, 
	`Active` INTEGER NOT NULL, 
	PRIMARY KEY (`Id`), 
	UNIQUE (`YearValue`)
);

CREATE TABLE IF NOT EXISTS md_company_country (
	`Id` INTEGER NOT NULL AUTO_INCREMENT, 
	`CompanyId` INTEGER NOT NULL, 
	`CountryId` INTEGER NOT NULL, 
	PRIMARY KEY (`Id`), 
	CONSTRAINT uq_company_country UNIQUE (`CompanyId`, `CountryId`), 
	FOREIGN KEY(`CompanyId`) REFERENCES md_company (`Id`), 
	FOREIGN KEY(`CountryId`) REFERENCES md_country (`Id`)
);

CREATE TABLE IF NOT EXISTS md_product_group (
	`Id` INTEGER NOT NULL AUTO_INCREMENT, 
	`Code` VARCHAR(20) NOT NULL, 
	`Name` VARCHAR(120) NOT NULL, 
	`CompanyId` INTEGER, 
	`LegacyId` INTEGER, 
	`Active` INTEGER NOT NULL, 
	PRIMARY KEY (`Id`), 
	CONSTRAINT uq_pg_code UNIQUE (`Code`), 
	FOREIGN KEY(`CompanyId`) REFERENCES md_company (`Id`)
);

CREATE TABLE IF NOT EXISTS md_product_reporting (
	`Id` INTEGER NOT NULL AUTO_INCREMENT, 
	`YearId` INTEGER NOT NULL, 
	`Code` VARCHAR(20) NOT NULL, 
	`Name` VARCHAR(120) NOT NULL, 
	`Flag` VARCHAR(2) NOT NULL, 
	`Active` INTEGER NOT NULL, 
	PRIMARY KEY (`Id`), 
	CONSTRAINT uq_pr_year_code UNIQUE (`YearId`, `Code`), 
	FOREIGN KEY(`YearId`) REFERENCES md_year (`Id`)
);

CREATE TABLE IF NOT EXISTS md_team (
	`Id` INTEGER NOT NULL AUTO_INCREMENT, 
	`Code` VARCHAR(20) NOT NULL, 
	`Name` VARCHAR(80) NOT NULL, 
	`CompanyId` INTEGER, 
	`LegacyId` INTEGER, 
	`Active` INTEGER NOT NULL, 
	PRIMARY KEY (`Id`), 
	CONSTRAINT uq_team_code UNIQUE (`Code`), 
	FOREIGN KEY(`CompanyId`) REFERENCES md_company (`Id`)
);

CREATE TABLE IF NOT EXISTS md_zone (
	`Id` INTEGER NOT NULL AUTO_INCREMENT, 
	`Code` VARCHAR(20) NOT NULL, 
	`Name` VARCHAR(120) NOT NULL, 
	`CountryId` INTEGER NOT NULL, 
	`LegacyId` INTEGER, 
	`Active` INTEGER NOT NULL, 
	PRIMARY KEY (`Id`), 
	CONSTRAINT uq_zone_code UNIQUE (`Code`), 
	FOREIGN KEY(`CountryId`) REFERENCES md_country (`Id`)
);

CREATE TABLE IF NOT EXISTS md_headquarter (
	`Id` INTEGER NOT NULL AUTO_INCREMENT, 
	`Code` VARCHAR(20) NOT NULL, 
	`Name` VARCHAR(120) NOT NULL, 
	`ZoneId` INTEGER NOT NULL, 
	`LegacyId` INTEGER, 
	`Active` INTEGER NOT NULL, 
	PRIMARY KEY (`Id`), 
	CONSTRAINT uq_hq_code UNIQUE (`Code`), 
	FOREIGN KEY(`ZoneId`) REFERENCES md_zone (`Id`)
);

CREATE TABLE IF NOT EXISTS md_product_reporting_sku (
	`Id` INTEGER NOT NULL AUTO_INCREMENT, 
	`ProductReportingId` INTEGER NOT NULL, 
	`SkuId` INTEGER NOT NULL, 
	`YearId` INTEGER NOT NULL, 
	PRIMARY KEY (`Id`), 
	CONSTRAINT uq_prs_year_sku UNIQUE (`YearId`, `SkuId`), 
	FOREIGN KEY(`ProductReportingId`) REFERENCES md_product_reporting (`Id`), 
	FOREIGN KEY(`SkuId`) REFERENCES `PRODUCT_MASTER` (`PRODUCT_ID`), 
	FOREIGN KEY(`YearId`) REFERENCES md_year (`Id`)
);

CREATE TABLE IF NOT EXISTS md_team_product_group (
	`Id` INTEGER NOT NULL AUTO_INCREMENT, 
	`YearId` INTEGER NOT NULL, 
	`TeamId` INTEGER NOT NULL, 
	`ProductGroupId` INTEGER NOT NULL, 
	PRIMARY KEY (`Id`), 
	CONSTRAINT uq_tpg UNIQUE (`YearId`, `TeamId`, `ProductGroupId`), 
	FOREIGN KEY(`YearId`) REFERENCES md_year (`Id`), 
	FOREIGN KEY(`TeamId`) REFERENCES md_team (`Id`), 
	FOREIGN KEY(`ProductGroupId`) REFERENCES md_product_group (`Id`)
);

CREATE TABLE IF NOT EXISTS md_team_headquarter (
	`Id` INTEGER NOT NULL AUTO_INCREMENT, 
	`YearId` INTEGER NOT NULL, 
	`TeamId` INTEGER NOT NULL, 
	`HeadquarterId` INTEGER NOT NULL, 
	PRIMARY KEY (`Id`), 
	CONSTRAINT uq_thq UNIQUE (`YearId`, `TeamId`, `HeadquarterId`), 
	FOREIGN KEY(`YearId`) REFERENCES md_year (`Id`), 
	FOREIGN KEY(`TeamId`) REFERENCES md_team (`Id`), 
	FOREIGN KEY(`HeadquarterId`) REFERENCES md_headquarter (`Id`)
);

CREATE TABLE IF NOT EXISTS md_territory (
	`Id` INTEGER NOT NULL AUTO_INCREMENT, 
	`Code` VARCHAR(20) NOT NULL, 
	`Name` VARCHAR(120) NOT NULL, 
	`HeadquarterId` INTEGER NOT NULL, 
	`LegacyId` INTEGER, 
	`Active` INTEGER NOT NULL, 
	PRIMARY KEY (`Id`), 
	CONSTRAINT uq_territory_code UNIQUE (`Code`), 
	FOREIGN KEY(`HeadquarterId`) REFERENCES md_headquarter (`Id`)
);

CREATE TABLE IF NOT EXISTS md_customer_assignment (
	`Id` INTEGER NOT NULL AUTO_INCREMENT, 
	`YearId` INTEGER NOT NULL, 
	`CustomerId` INTEGER NOT NULL, 
	`TerritoryId` INTEGER NOT NULL, 
	`TeamId` INTEGER NOT NULL, 
	`ProductGroupId` INTEGER NOT NULL, 
	`SkuId` INTEGER NOT NULL, 
	PRIMARY KEY (`Id`), 
	CONSTRAINT uq_ca_year_cust_sku UNIQUE (`YearId`, `CustomerId`, `SkuId`), 
	FOREIGN KEY(`YearId`) REFERENCES md_year (`Id`), 
	FOREIGN KEY(`CustomerId`) REFERENCES `CUSTOMER_MASTER` (`CUSTOMER_ID`), 
	FOREIGN KEY(`TerritoryId`) REFERENCES md_territory (`Id`), 
	FOREIGN KEY(`TeamId`) REFERENCES md_team (`Id`), 
	FOREIGN KEY(`ProductGroupId`) REFERENCES md_product_group (`Id`), 
	FOREIGN KEY(`SkuId`) REFERENCES `PRODUCT_MASTER` (`PRODUCT_ID`)
);

CREATE INDEX ix_ca_territory ON md_customer_assignment (`YearId`, `TerritoryId`);

CREATE TABLE IF NOT EXISTS md_employee_assignment (
	`Id` INTEGER NOT NULL AUTO_INCREMENT, 
	`YearId` INTEGER NOT NULL, 
	`EmployeeId` INTEGER NOT NULL, 
	`TerritoryId` INTEGER NOT NULL, 
	`ProductGroupId` INTEGER NOT NULL, 
	`SkuId` INTEGER NOT NULL, 
	PRIMARY KEY (`Id`), 
	CONSTRAINT uq_ea_year_emp_terr_sku UNIQUE (`YearId`, `EmployeeId`, `TerritoryId`, `SkuId`), 
	FOREIGN KEY(`YearId`) REFERENCES md_year (`Id`), 
	FOREIGN KEY(`EmployeeId`) REFERENCES `EMPLOYEE_MASTER` (`EMPLOYEE_ID`), 
	FOREIGN KEY(`TerritoryId`) REFERENCES md_territory (`Id`), 
	FOREIGN KEY(`ProductGroupId`) REFERENCES md_product_group (`Id`), 
	FOREIGN KEY(`SkuId`) REFERENCES `PRODUCT_MASTER` (`PRODUCT_ID`)
);

CREATE INDEX ix_ea_territory ON md_employee_assignment (`YearId`, `TerritoryId`);
